// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbj-3P5ywAu3-FNnaJDIv-fXBnRYIIqAo',
    appId: '1:708244412702:web:e215f200dd6ca3f108910f',
    messagingSenderId: '708244412702',
    projectId: 'test-app-51384',
    authDomain: 'test-app-51384.firebaseapp.com',
    storageBucket: 'test-app-51384.firebasestorage.app',
    measurementId: 'G-C8VG5VCG5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVfU5xuvzDzsby6PkWQ3FGJnpydakkcoU',
    appId: '1:708244412702:android:a1b4a5648f81ee1608910f',
    messagingSenderId: '708244412702',
    projectId: 'test-app-51384',
    storageBucket: 'test-app-51384.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdEwmN4GYOyEPygOQgfmhupjDan68wJfA',
    appId: '1:708244412702:ios:1a3e26387688b3df08910f',
    messagingSenderId: '708244412702',
    projectId: 'test-app-51384',
    storageBucket: 'test-app-51384.firebasestorage.app',
    androidClientId: '708244412702-vkpt25pruenbcg4tg6e97mq600oj4cn0.apps.googleusercontent.com',
    iosClientId: '708244412702-815btichbdojqpgicfh86elsob9avb73.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbj-3P5ywAu3-FNnaJDIv-fXBnRYIIqAo',
    appId: '1:708244412702:web:5fb584b80eaa7b6608910f',
    messagingSenderId: '708244412702',
    projectId: 'test-app-51384',
    authDomain: 'test-app-51384.firebaseapp.com',
    storageBucket: 'test-app-51384.firebasestorage.app',
    measurementId: 'G-6ME7SSDTMJ',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdEwmN4GYOyEPygOQgfmhupjDan68wJfA',
    appId: '1:708244412702:ios:1a3e26387688b3df08910f',
    messagingSenderId: '708244412702',
    projectId: 'test-app-51384',
    storageBucket: 'test-app-51384.firebasestorage.app',
    androidClientId: '708244412702-vkpt25pruenbcg4tg6e97mq600oj4cn0.apps.googleusercontent.com',
    iosClientId: '708244412702-815btichbdojqpgicfh86elsob9avb73.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
