/// Words that point to an expense category, used to suggest one from what the
/// user said or typed, or from a receipt.
///
/// Written in lowercase, without apostrophes; other punctuation counts as a
/// space, so `7-eleven` is written `7 eleven`. A phrase only matches whole
/// words, and a longer phrase wins over a shorter one inside it, so
/// `grab food` is Food even though `grab` alone is Transportation.
///
/// Add store names and Taglish words here as they come up. A category left
/// out of the list is simply never suggested.
const Map<String, List<String>> categoryKeywords = {
  'Food': [
    'food',
    'foods',
    'pagkain',
    'kain',
    'kumain',
    'breakfast',
    'almusal',
    'lunch',
    'tanghalian',
    'dinner',
    'hapunan',
    'merienda',
    'meryenda',
    'snack',
    'snacks',
    'ulam',
    'kanin',
    'rice',
    'bigas',
    'coffee',
    'kape',
    'milk tea',
    'milktea',
    'bread',
    'tinapay',
    'pandesal',
    'grocery',
    'groceries',
    'palengke',
    'market',
    'fruits',
    'prutas',
    'gulay',
    'vegetables',
    'meat',
    'karne',
    'isda',
    'fish',
    'chicken',
    'manok',
    'pizza',
    'burger',
    'fries',
    'siopao',
    'shawarma',
    'samgyup',
    'samgyupsal',
    'lugaw',
    'tapsilog',
    'silog',
    'karinderya',
    'carinderia',
    'canteen',
    'restaurant',
    'resto',
    'cafe',
    'bakery',
    'drinks',
    'softdrinks',
    'jollibee',
    'mcdo',
    'mcdonalds',
    'kfc',
    'chowking',
    'mang inasal',
    'greenwich',
    'red ribbon',
    'goldilocks',
    'starbucks',
    'dunkin',
    'tim hortons',
    'shakeys',
    'yellow cab',
    'maxs',
    'bonchon',
    'army navy',
    'potato corner',
    'zagu',
    'coco',
    'chatime',
    'gong cha',
    '7 eleven',
    'seven eleven',
    'ministop',
    'family mart',
    'lawson',
    'alfamart',
    'puregold',
    'savemore',
    'sm supermarket',
    'sm hypermarket',
    'robinsons supermarket',
    'waltermart',
    'landers',
    's r',
    'snr',
    'grab food',
    'grabfood',
    'foodpanda',
    'food panda',
  ],
  'Transportation': [
    'transportation',
    'transpo',
    'commute',
    'pamasahe',
    'fare',
    'grab',
    'angkas',
    'joyride',
    'move it',
    'jeep',
    'jeepney',
    'tricycle',
    'trike',
    'bus',
    'taxi',
    'uber',
    'lrt',
    'mrt',
    'pnr',
    'train',
    'tren',
    'beep card',
    'gas',
    'gasoline',
    'diesel',
    'fuel',
    'petron',
    'shell',
    'caltex',
    'seaoil',
    'phoenix',
    'parking',
    'toll',
    'autosweep',
    'easytrip',
    'ferry',
    'boat',
    'bangka',
    'flight',
    'airfare',
    'plane ticket',
    'lalamove',
  ],
  'Shopping': [
    'shopping',
    'shopee',
    'lazada',
    'tiktok shop',
    'zalora',
    'mall',
    'clothes',
    'damit',
    'shirt',
    't shirt',
    'tshirt',
    'pants',
    'shorts',
    'dress',
    'shoes',
    'sapatos',
    'sneakers',
    'tsinelas',
    'slippers',
    'bag',
    'gadget',
    'gadgets',
    'phone case',
    'charger',
    'earphones',
    'headphones',
    'airpods',
    'uniqlo',
    'h m',
    'penshoppe',
    'bench',
    'sm store',
    'ace hardware',
    'handyman',
    'true value',
    'ikea',
    'makeup',
    'skincare',
    'cosmetics',
    'perfume',
    'shampoo',
    'sabon',
    'soap',
    'toiletries',
  ],
  'Bills': [
    'bill',
    'bills',
    'meralco',
    'electric',
    'electricity',
    'kuryente',
    'maynilad',
    'manila water',
    'water bill',
    'pldt',
    'globe',
    'smart load',
    'smart prepaid',
    'smart postpaid',
    'smart bill',
    'dito',
    'tnt',
    'converge',
    'sky cable',
    'skycable',
    'internet',
    'wifi',
    'postpaid',
    'load',
    'prepaid load',
    'rent',
    'renta',
    'upa',
    'association dues',
    'dues',
    'sss',
    'philhealth',
    'pag ibig',
    'pagibig',
    'insurance',
  ],
  'Entertainment': [
    'entertainment',
    'netflix',
    'spotify',
    'youtube premium',
    'disney',
    'hbo',
    'prime video',
    'viu',
    'movie',
    'movies',
    'sine',
    'cinema',
    'concert',
    'game',
    'games',
    'steam',
    'mobile legends',
    'ml diamonds',
    'diamonds',
    'codm',
    'valorant',
    'genshin',
    'roblox',
    'playstation',
    'nintendo',
    'xbox',
    'karaoke',
    'videoke',
    'inuman',
    'beer',
    'gimik',
    'outing',
    'resort',
    'arcade',
    'timezone',
    'toms world',
  ],
  'Healthcare': [
    'health',
    'healthcare',
    'medicine',
    'medicines',
    'gamot',
    'vitamins',
    'biogesic',
    'neozep',
    'bioflu',
    'doctor',
    'doktor',
    'check up',
    'checkup',
    'consultation',
    'clinic',
    'klinika',
    'hospital',
    'ospital',
    'dentist',
    'dental',
    'laboratory',
    'lab test',
    'x ray',
    'xray',
    'optical',
    'eyeglasses',
    'medical',
    'pharmacy',
    'botika',
    'drugstore',
    'mercury drug',
    'southstar',
    'rose pharmacy',
    'the generics pharmacy',
    'generika',
    'tgp',
    'watsons',
  ],
  'Education': [
    'education',
    'tuition',
    'matrikula',
    'school',
    'eskwela',
    'paaralan',
    'book',
    'books',
    'libro',
    'notebook',
    'notebooks',
    'school supplies',
    'national bookstore',
    'fully booked',
    'pencil',
    'ballpen',
    'bond paper',
    'printing',
    'print',
    'xerox',
    'photocopy',
    'course',
    'seminar',
    'review center',
    'enrollment',
    'school uniform',
    'thesis',
  ],
  'Pets': [
    'pet',
    'pets',
    'dog',
    'dogs',
    'aso',
    'cat',
    'cats',
    'pusa',
    'vet',
    'veterinary',
    'beterinaryo',
    'dog food',
    'cat food',
    'pet food',
    'pagkain ng aso',
    'pagkain ng pusa',
    'pet supplies',
    'pedigree',
    'whiskas',
    'grooming',
    'cat litter',
    'litter',
    'pet express',
  ],
};

/// Occasions that hint at a category without saying what was paid for. They
/// only count when nothing in [categoryKeywords] matches, so "dinner date" is
/// still Food and "date at Jollibee" too, while "date with my girlfriend" is
/// going out.
///
/// "date" alone isn't listed: it is also a calendar date, printed on nearly
/// every receipt.
const Map<String, List<String>> occasionKeywords = {
  'Entertainment': [
    'date with',
    'date night',
    'first date',
    'nag date',
    'nagdate',
    'mag date',
    'magdate',
    'dinate',
    'date namin',
    'date kami',
  ],
};
